#!/usr/bin/env python3

num = input('Insert number here. ')
if (num % 3 != 0 && num % 5 != 0);
 print(num) 
elif (num % 3 == 0);
 print(fizz)
elif (num % 5 == 0);
 print(buzz)
 elif (num % 3 == 0 && num % 5 == 0)
